<?php

/**
 * @file
 * Primary module hooks for OpenID Connect Claims module.
 */

/**
 * Implements hook_oauth2_server_user_claims().
 */
function openid_connect_claims_oauth2_server_claims(\Drupal\user\UserInterface $account, array $requested_scopes) {
  $claims = [
    // @todo Make this field configurable.
    'name' => $account->getAccountName(),
  ];

  // The profile scope.
  // @see https://openid.net/specs/openid-connect-core-1_0.html#rfc.section.5.4
  if (in_array('profile', $requested_scopes)) {
    $claims += [
      'email' => $account->getEmail(),
      // @todo Make these fields configurable.
      //'family_name' => '',
      //'given_name' => '',
      //'middle_name' => '',
      'nickname' => $account->getAccountName(),
      'preferred_username' => $account->getAccountName(),
      'profile' => $account->toUrl('canonical', ['absolute' => TRUE]),
      // @todo Make these fields configurable.
      'picture' => '',
      //'website' => '',
      //'gender' => '',
      //'birthdate' => '',
      'zoneinfo' => $account->getTimeZone(),
      'locale' => $account->getPreferredLangcode(),
      'updated_at' => $account->getChangedTime(),
    ];
  }

  // The email scope.
  // @see https://openid.net/specs/openid-connect-core-1_0.html#rfc.section.5.4
  if (in_array('profile', $requested_scopes)) {
    $claims += [
      'email' => $account->getEmail(),
      'email_verified' => \Drupal::config('user.settings')->get('verify_mail'),
    ];
  }

  // The address scope.
  // @see https://openid.net/specs/openid-connect-core-1_0.html#rfc.section.5.4
  if (in_array('profile', $requested_scopes)) {
    $claims += [
      // @todo Make this field configurable.
      //'address' => [
      //  'formatted' => '',
      //  'street_address' => '',
      //  'locality' => '',
      //  'region' => '',
      //  'postal_code' => '',
      //  'country' => '',
      //],
    ];
  }

  // The phone scope.
  // @see https://openid.net/specs/openid-connect-core-1_0.html#rfc.section.5.4
  if (in_array('profile', $requested_scopes)) {
    $claims += [
      // @todo Make this field configurable.
      //'phone_number' => '',
      //'phone_number_verified' => '',
    ];
  }

  return $claims;
}
